### ISSUE TITLE
Implémentation d'un auto update

### ISSUE THREAD

**Issue by thomas92fr** [thomas92fr/mcp-toolskit#4]
# Mise en place d'un système d'installation et de mise à jour via GitHub

## Contexte du projet

Le projet est un serveur MCP (Model Context Protocol) qui met des outils à disposition de ClaudeDesktop avec les caractéristiques suivantes :

- Utilise .NET v9.0
- Utilise Serilog pour la génération de logs
- Basé sur ModelContextProtocol.NET pour la partie serveur MCP
- Structure du projet :
  - Dossier 'mcp-toolskit' : projet du serveur MCP
  - Dossier 'mcp-toolskit-tests' : projet des tests unitaires

### Solutions écartées

1. **Squirrel.Windows**
   - Plus maintenu depuis plusieurs années
   - Non recommandé pour les projets modernes

2. **Clowd.Squirrel**
   - Fork moderne de Squirrel.Windows
   - Solution alternative mais pas la plus optimale

3. **MSIX**
   - Solution officielle Microsoft
   - Plus complexe à mettre en place

### Solution retenue : AutoUpdater.NET

Avantages :
- Activement maintenu (dernière mise à jour janvier 2024)
- Support complet de .NET 6+
- Compatible avec GitHub Releases
- Simple à mettre en place

### 1. Installation du package NuGet

```xml
<!-- Dans le fichier mcp-toolskit.csproj -->
<ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.8.5" />
</ItemGroup>
```

### 2. Classe UpdateManager

```csharp
using AutoUpdaterDotNET;
using Serilog;

public class UpdateManager
{
    private readonly ILogger _logger;
    private const string UPDATE_URL = "https://github.com/votre-username/mcp-toolskit/releases/latest/download/update.xml";

    public UpdateManager(ILogger logger)
    {
        _logger = logger;
        ConfigureAutoUpdater();
    }

    private void ConfigureAutoUpdater()
    {
        AutoUpdater.RunUpdateAsAdmin = false;
        AutoUpdater.CheckForUpdateEvent += AutoUpdaterOnCheckForUpdateEvent;
        AutoUpdater.ApplicationExitEvent += AutoUpdater_ApplicationExitEvent;
        
        AutoUpdater.ReportError = (exception) =>
        {
            _logger.Error(exception, "Erreur lors de la mise à jour");
        };
    }

    private void AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
    {
        try
        {
            if (args.IsUpdateAvailable)
            {
                _logger.Information($"Mise à jour disponible: {args.CurrentVersion} -> {args.InstalledVersion}");
            }
            else
            {
                _logger.Information("Aucune mise à jour disponible");
            }
        }
        catch (Exception ex)
        {
            _logger.Error(ex, "Erreur lors de la vérification des mises à jour");
        }
    }

    private void AutoUpdater_ApplicationExitEvent()
    {
        _logger.Information("Application fermée pour mise à jour");
        Environment.Exit(0);
    }

    public void CheckForUpdates()
    {
        try
        {
            AutoUpdater.Start(UPDATE_URL);
        }
        catch (Exception ex)
        {
            _logger.Error(ex, "Erreur lors du démarrage de la vérification des mises à jour");
        }
    }
}
```

### 3. Fichier de configuration des mises à jour

```xml
<!-- update.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<item>
    <version>1.0.0.0</version>
    <url>https://github.com/votre-username/mcp-toolskit/releases/download/v1.0.0/MCPToolsKit-1.0.0.zip</url>
    <mandatory>false</mandatory>
    <checksum algorithm="MD5">votre_md5_checksum</checksum>
    <changelog>
        https://github.com/votre-username/mcp-toolskit/releases/tag/v1.0.0
    </changelog>
</item>
```

### 4. Intégration dans Program.cs

```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .WriteTo.File("logs/mcp-toolskit.log")
            .CreateLogger();

        try
        {
            var updateManager = new UpdateManager(Log.Logger);
            updateManager.CheckForUpdates();

            // Code existant...
        }
        catch (Exception ex)
        {
            Log.Logger.Error(ex, "Erreur lors de l'exécution de l'application");
        }
    }
}
```

### 5. Configuration GitHub Actions

```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Build
      run: |
        dotnet restore
        dotnet publish mcp-toolskit/mcp-toolskit.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
        
    - name: Create ZIP Archive
      run: |
        Compress-Archive -Path "./mcp-toolskit/bin/Release/net9.0/win-x64/publish/*" -DestinationPath "MCPToolsKit.zip"
        
    - name: Calculate MD5
      id: md5
      run: |
        $md5 = (Get-FileHash MCPToolsKit.zip -Algorithm MD5).Hash.ToLower()
        echo "::set-output name=hash::$md5"
        
    - name: Update update.xml
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        $content = @"
        <?xml version="1.0" encoding="UTF-8"?>
        <item>
            <version>$version</version>
            <url>https://github.com/${{ github.repository }}/releases/download/v$version/MCPToolsKit.zip</url>
            <mandatory>false</mandatory>
            <checksum algorithm="MD5">${{ steps.md5.outputs.hash }}</checksum>
            <changelog>https://github.com/${{ github.repository }}/releases/tag/v$version</changelog>
        </item>
        "@
        Set-Content -Path update.xml -Value $content
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          MCPToolsKit.zip
          update.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Processus de publication d'une nouvelle version

1. Mettre à jour la version dans le fichier .csproj
2. Créer un tag Git : `git tag v1.0.0`
3. Pousser le tag : `git push origin v1.0.0`
4. GitHub Actions créera automatiquement :
   - La release avec le ZIP des binaires
   - Le fichier update.xml mis à jour
   
L'application vérifiera automatiquement les mises à jour au démarrage et proposera à l'utilisateur de les installer si disponibles.
